INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(1, '11', 'ACTIVOS', '11');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(2, '1111', 'CAJAS', '11');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(3, '1111001', 'FONDO FIJO', '11');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(4, '1112', 'BANCOS', '11');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(5, '1112001', 'BBVA BANCOMER CTA ****9210 OLIMPO', '11');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(6, '21', 'PASIVO CIRCULANTE', '21');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(7, '22', 'PASIVO FIJO', '22');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(8, '23', 'PASIVO DIFERIDO', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(9, '2115', 'APARTADOS', '21');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(10, '2115001', 'FONDO DE RESERVA INICIAL', '21');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(11, '2311', 'CUOTAS DE MANTENIMIENTO ORDINARIAS', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(12, '2312', 'CUOTAS DE MANTENIMIENTO EXTRAORDINARIAS', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(13, '2313', 'CUOTAS DE FONDO DE RESERVA', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(14, '2314', 'PENAS POR MORA DE CUOTA ORDINARIA', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(15, '2315', 'PENAS POR MORA DE CUOTA EXTRAORDINARIA', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(16, '2316', 'OTRAS PREVISIONES POR CUOTAS', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(17, '231601', 'CUOTA ADMINISTRACION DE GAS', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(18, '2319', 'ANTICIPOS DE CUOTAS DE MANTENIMIENTO Y FONDO DE RESERVA', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(19, '2318', 'DEPOSITOS Y REMESAS POR IDENTIFICAR', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(20, '2317', 'CUOTA ALQUILER DE TERRAZA', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(21, '41', 'INGRESOS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(22, '4111', 'CUOTAS DE MANTENIMIENTO ORDINARIAS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(23, '4112', 'CUOTAS DE MANTENIMIENTO EXTRAORDINARIAS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(24, '4113', 'CUOTAS FONDO DE RESERVA', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(25, '4114', 'PENAS POR MORA ORDINARIAS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(26, '4115', 'PENAS POR MORA EXTRAORDINARIAS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(27, '4116', 'OTROS INGRESOS POR CUOTAS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(28, '4117', 'INGRESOS POR ALQUILER DE TERRAZA', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(29, '4118', 'OTROS INGRESOS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(30, '51', 'EGRESOS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(31, '5111', 'GASTOS DE ADMINISTRACION', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(32, '511101', 'SERVICIOS PERSONALES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(33, '511102', 'PRESTACIONES AL PERSONAL', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(34, '511103', 'IMPUESTOS Y APORTACIONES SOBRE SUELDOS Y SALARIOS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(35, '511104', 'HONORARIOS A PERSONAS FISICAS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(36, '511105', 'HONORARIOS A PERSONAS MORALES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(37, '511106', 'SERVICIOS GENERALES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(38, '51110601', 'PAPELERIA Y ARTICULOS DE OFICINA', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(39, '511107', 'IMPUESTOS Y DERECHOS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(40, '5112', 'GASTOS DE OPERACION', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(41, '511201', 'SERVICIOS PERSONALES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(42, '511202', 'PRESTACIONES AL PERSONAL', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(43, '511203', 'IMPUESTOS Y APORTACIONES SOBRE SUELDOS Y SALARIOS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(44, '511204', 'SERVICIOS GENERALES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(45, '51120401', 'ENERGIA ELECTRICA AREAS COMUNES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(46, '51120402', 'VIGILANCIA Y SEGURIDAD', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(47, '51120403', 'RECOLECCION DE BASURA', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(48, '5113', 'GASTOS DE MANTENIMIENTO', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(49, '5114', 'GASTOS DE INVERSION Y EQUIPAMIENTO MENOR', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(50, '5115', 'GASTOS FINANCIEROS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(51, '5116', 'OTROS EGRESOS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(52, '511301', 'MANTENIMIENTO Y CONSERVACION', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(53, '2111', 'PROVEEDORES', '21');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(54, '2112', 'CUENTAS POR PAGAR CORTO PLAZO', '21');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(55, '51120404', 'LIMPIEZA AREAS COMUNES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(56, '51110401', 'HONORARIOS ADMINISTRACION', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(57, '511501', 'INTERESES Y COMISIONES BANCARIAS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(58, '51130101', 'MANTENIMIENTO PREVENTIVO A ELEVADORES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(59, '51130102', 'LAVADO DE CISTERNAS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(60, '51130103', 'MANTENIMIENTO A CCTV', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(61, '51130104', 'CARGA DE EXTINTORES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(62, '51130105', 'MANTENIMIENTO BOMBAS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(63, '51130106', 'IMPERMEABILIZACION', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(64, '51130107', 'PLOMERIA REPARACION TUBO PVC EN TORRE C PISO 3', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(65, '51130108', 'ALBANILERIA', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(66, '51130109', 'CERRAJERIA', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(67, '411601', 'CUOTA ADMINISTRACION DE GAS', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(69, '51120405', 'ADMINISTRACION DE GAS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(70, '51130110', 'REPARACIONES EN GENERAL', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(71, '511205', 'SUMINISTRO DE AGUA POR PIPAS', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(72, '411202', 'CUOTA EXTRAORDINARIA TECHADO DE TERRAZA', '41');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(73, '51130111', 'LAMPARAS Y SENSORES', '5113');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(74, '51120406', 'SERVICIO TELEFONICO', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(75, '231202', 'CUOTA EXTRAORDINARIA TECHADO TERRAZA', '2312');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(76, '51130111', 'EQUIPO ALUMBRADO AREAS COMUNES', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(78, '2316', 'OTRAS MULTAS', '23');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(79, '511401', 'COMPRA DE CONTROL REMOTO ABREPUERTA', '5114');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(80, '511206', 'PAGOS A TESORERIA DE LA CDMX', '51');
INSERT INTO `cuenta_contable` (`id`, `num_cuenta`, `descripcion`, `clave_mayor`) VALUES(81, '51120407', 'FUMIGACION', '51');
