INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(1, 'MANTENIMIENTO', '500.00', 22, 1213, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(2, 'MANTENIMIENTO', '500.00', 22, 1214, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(3, 'MANTENIMIENTO', '500.00', 22, 1215, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(4, 'MANTENIMIENTO', '500.00', 22, 1216, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(5, 'MANTENIMIENTO', '500.00', 22, 1217, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(6, 'MANTENIMIENTO', '500.00', 22, 1218, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(7, 'MANTENIMIENTO', '500.00', 22, 1219, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(8, 'MANTENIMIENTO', '1500.00', 22, 1220, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(9, 'OTROS INGRESOS', '0.50', 29, 1220, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(10, 'MANTENIMIENTO', '500.00', 22, 1221, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(11, 'MANTENIMIENTO', '500.00', 22, 1222, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(12, 'PINTURA', '1000.00', 23, 1222, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(13, 'MANTENIMIENTO', '500.00', 22, 1223, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(14, 'MANTENIMIENTO', '500.00', 11, 1224, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(15, 'MANTENIMIENTO', '500.00', 11, 1225, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(16, 'MANTENIMIENTO', '500.00', 11, 1226, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(17, 'MANTENIMIENTO', '500.00', 11, 1227, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(18, 'MANTENIMIENTO', '500.00', 11, 1228, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(19, 'MANTENIMIENTO', '500.00', 11, 1229, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(20, 'MANTENIMIENTO', '500.00', 22, 1230, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(21, 'OTROS INGRESOS', '50.00', 29, 1230, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(22, 'MANTENIMIENTO', '500.00', 22, 1231, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(23, 'MANTENIMIENTO', '1000.00', 22, 1232, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(24, 'MANTENIMIENTO', '500.00', 22, 1233, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(25, 'MANTENIMIENTO', '500.00', 22, 1234, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(26, 'MANTENIMIENTO', '500.00', 22, 1235, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(27, 'MANTENIMIENTO', '500.00', 22, 1236, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(28, 'MANTENIMIENTO', '500.00', 22, 1237, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(29, 'MANTENIMIENTO', '410.00', 22, 1238, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(30, 'MANTENIMIENTO', '500.00', 22, 1239, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(31, 'MANTENIMIENTO', '500.00', 22, 1240, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(32, 'MANTENIMIENTO', '500.00', 22, 1241, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(33, 'PINTURA', '1000.00', 23, 1241, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(34, 'MANTENIMIENTO', '500.00', 22, 1242, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(35, 'MANTENIMIENTO', '500.00', 22, 1243, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(36, 'MANTENIMIENTO', '500.00', 25, 1244, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(37, 'MANTENIMIENTO', '500.00', 22, 1245, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(38, 'MANTENIMIENTO', '500.00', 22, 1246, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(39, 'MANTENIMIENTO', '500.00', 22, 1247, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(40, 'MANTENIMIENTO', '500.00', 22, 1248, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(41, 'MANTENIMIENTO', '500.00', 22, 1249, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(42, 'MANTENIMIENTO', '1000.00', 22, 1250, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(43, 'MANTENIMIENTO', '500.00', 22, 1251, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(44, 'MANTENIMIENTO', '1000.00', 22, 1252, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(45, 'PAGO SERVICIOS', '16712.00', 30, 1253, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(46, 'MANTENIMIENTO', '500.00', 22, 1254, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(47, 'MANTENIMIENTO', '500.00', 22, 1255, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(48, 'MANTENIMIENTO', '500.00', 22, 1256, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(49, 'PINTURA', '1000.00', 23, 1257, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(50, 'MANTENIMIENTO', '500.00', 22, 1258, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(51, 'PINTURA', '1000.00', 23, 1258, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(52, 'MANTENIMIENTO', '500.00', 22, 1259, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(53, 'OTROS INGRESOS', '50.00', 29, 1259, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(54, 'MANTENIMIENTO', '500.00', 22, 1260, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(55, 'MANTENIMIENTO', '500.00', 22, 1261, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(56, 'PINTURA', '1000.00', 23, 1262, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(57, 'PINTURA', '1010.00', 23, 1263, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(58, 'PINTURA', '1010.00', 23, 1264, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(59, 'PINTURA', '700.00', 12, 1265, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(60, 'PINTURA', '1000.00', 23, 1266, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(61, 'OTROS INGRESOS', '3730.00', 29, 1267, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(62, 'MANTENIMIENTO', '500.00', 22, 1268, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(63, 'MANTENIMIENTO', '500.00', 22, 1269, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(64, 'MANTENIMIENTO', '500.00', 22, 1270, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(65, 'MANTENIMIENTO', '500.00', 22, 1271, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(66, 'PINTURA', '1000.00', 23, 1272, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(67, 'PINTURA', '1000.00', 23, 1273, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(68, 'MANTENIMIENTO', '200.00', 22, 1274, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(69, 'PINTURA', '1000.00', 23, 1275, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(70, 'OTROS INGRESOS', '3500.00', 27, 1276, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(71, 'PINTURA', '2010.00', 23, 1277, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(72, 'PAGO SERVICIOS', '14614.00', 30, 1278, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(73, 'RETIRO EN EFECTIVO', '3900.00', 51, 1579, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(74, 'VIGILANCIA 1RA QUINCENA DE MAYO', '2900.00', 46, 1580, 2);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(75, 'SR FELIPE', '628.00', 51, 1577, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(76, 'LIMPIEZA 1RA QUINCENA DE MAYO', '2050.00', 55, 1581, 3);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(77, 'RECOLECCION BASURA 1RA QUINCENA DE MAYO', '500.00', 47, 1582, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(78, 'ADMINISTRACION 1RA QNA DE MAYO', '3500.00', 56, 1583, 4);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(79, 'SEGURO PATRONAL', '800.00', 42, 1584, 3);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(80, 'VIGILANCIA SR LECHUGA 1RA QNA DE MAYO', '4240.00', 46, 1585, 5);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(81, 'ANTICIPO PINTURA EDIFICIO', '4500.00', 52, 1586, 1);
INSERT INTO `sadi_detalle_movimiento` (`id`, `descripcion`, `monto`, `cuenta_contable_id`, `movimiento_id`, `proveedor_id`) VALUES(82, 'SEGURO PATRONAL', '501.60', 42, 1587, 3);
