INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(1, 'PAGO EN EFECTIVO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(2, 'DEPOSITO EN EFECTIVO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(3, 'DEPOSITO SALVO BUEN COBRO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(4, 'SPEI ');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(5, 'PAGO CUENTA DE TERCEROS');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(6, 'TRANSFERENCIA');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(7, 'CHEQUE');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(8, 'CHEQUE DEPOSITADO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(9, 'RETIRO CAJERO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(10, 'DEPOSITO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(11, 'CHEQUE PAGADO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(12, 'DEPOSITO CON DOCUMENTOS');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(13, 'COMISION');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(14, 'PAGO CHEQUE EFECTIVO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(15, 'SERV BANCA INTERNET');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(16, 'IVA COM SERV BCA INTERNET');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(17, 'DEP CHEQUES DE OTRO BANCO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(18, 'TRASPASO CUENTAS PROPIAS');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(19, 'TRASPASO ENTRE CUENTAS ');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(20, 'PAGO TARJETA DE CREDITO ');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(21, 'CARGO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(22, 'DEPOSITO EFECTIVO PRACTIC');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(23, 'EXENCION ');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(24, 'EXENTO MULTAS');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(25, 'ABONO');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(26, 'SPEI RECIBIDO BANAMEX');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(27, 'CARGO MES');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(28, 'DEPOSITO INVERSION');
INSERT INTO `tipo_movimiento` (`id`, `descripcion`) VALUES(29, 'PAGO RECIBIDO DE');
